# Generated by Django 6.0.2 on 2026-02-26 21:15

import django.core.validators
import django.db.models.deletion
import repository.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarlyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(help_text='Comma-separated author names', max_length=500)),
                ('publication_year', models.IntegerField()),
                ('file', models.FileField(upload_to=repository.models.scholarly_work_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=50)),
                ('converted_pdf', models.FileField(blank=True, null=True, upload_to='converted_pdfs/')),
                ('conversion_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('conversion_progress', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scholarly Work',
                'verbose_name_plural': 'Scholarly Works',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('scholarly_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='repository.scholarlywork')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'scholarly_work')},
            },
        ),
    ]
